// Public Q_INVOKABLE surface for CoreController (included in class public section).

    Q_INVOKABLE void clearCatalogFilters();
    Q_INVOKABLE void setCatalogFilters(int, int, int, bool, const QString&, int = 0);
    Q_INVOKABLE void applyCatalogPresentation(int, int, int, int, bool, const QString&, int = 0);
    Q_INVOKABLE QVariantList pluginEntries() const;
    Q_INVOKABLE bool isPluginInstalledOnDisk(const QString&) const;
    Q_INVOKABLE void browsePluginArach();
    Q_INVOKABLE bool installPluginArach(const QUrl&);
    Q_INVOKABLE bool uninstallPlugin(const QString&);
    Q_INVOKABLE void refreshOfficialPlugins();
    Q_INVOKABLE void installOfficialPlugin(const QString&);
    Q_INVOKABLE void openPluginsFolder();
    Q_INVOKABLE void rescanPlugins();
    Q_INVOKABLE void launchGame(const QString&);
    Q_INVOKABLE void stopRunningGame();
    Q_INVOKABLE void searchCatalog(const QString&, const QString&);
    Q_INVOKABLE void installCatalogEntry(const QString&, const QString& = {},
                                         const QVariantList& = {}, const QString& = {});
    Q_INVOKABLE void installCatalogAddon(const QString&, const QString&);
    Q_INVOKABLE void installDownloadedCatalogAddon(const QString&, const QString&);
    Q_INVOKABLE bool isCatalogAddonInstalled(const QString&, const QString&) const;
    Q_INVOKABLE void updateCatalogEntry(const QString&);
    Q_INVOKABLE void setGameAutoUpdate(const QString&, bool);
    Q_INVOKABLE void setGameLaunchArgs(const QString&, const QString&);
    Q_INVOKABLE void setGameExecutableOverride(const QString&, const QString&);
    Q_INVOKABLE void setGameProtonId(const QString&, const QString&);
    Q_INVOKABLE void setGameOnlineFixEnabled(const QString&, bool);
    Q_INVOKABLE void refreshAvailableProtons();
    Q_INVOKABLE void moveProtonInPriority(const QString&, int);
    Q_INVOKABLE QString protonNameForId(const QString&) const;
    Q_INVOKABLE void downloadProtonGe();
    Q_INVOKABLE void refreshProtonLatestRelease();
    Q_INVOKABLE bool needsProtonOnPlatform() const;
    Q_INVOKABLE bool ensureProtonReady();
    Q_INVOKABLE bool needsInstallLocationChoice() const;
    Q_INVOKABLE QString browseGameExecutable(const QString& = {});
    Q_INVOKABLE QString browseStorageFolder();
    Q_INVOKABLE QVariantMap gameRuntimeContainerInfo(const QString&) const;
    Q_INVOKABLE void openGameRuntimeContainer(const QString&);
    Q_INVOKABLE void removeGame(const QString&, bool = true);
    Q_INVOKABLE void removeEntry(const QString&, bool = true);
    Q_INVOKABLE void moveGame(const QString&, const QString&);
    Q_INVOKABLE QVariantList gamesOnLibrary(const QString&) const;
    Q_INVOKABLE bool removeStorageLibrary(const QString&, bool force = false);
    Q_INVOKABLE int scanInstalledGames();
    Q_INVOKABLE bool isEntryPlayable(const QString&) const;
    Q_INVOKABLE bool isEntryDownloadComplete(const QString&) const;
    Q_INVOKABLE bool entryDownloadFilesExist(const QString&) const;
    Q_INVOKABLE QVariantMap entryDetails(const QString&) const;
    Q_INVOKABLE void checkUpdates();
    Q_INVOKABLE void cancelJob(const QString&);
    Q_INVOKABLE void toggleJobPause(const QString&);
    Q_INVOKABLE void removeJob(const QString&);
    Q_INVOKABLE void retryJob(const QString&);
    Q_INVOKABLE void retryInstall(const QString&);
    Q_INVOKABLE bool canRetryJobInstall(const QString&) const;
    Q_INVOKABLE bool canManualInstallJob(const QString&) const;
    Q_INVOKABLE void openJobDownloadFolder(const QString&);
    Q_INVOKABLE void confirmManualInstall(const QString&);
    Q_INVOKABLE QString browseInstallFolder(const QString& = {});
    Q_INVOKABLE void clearFinishedJobs();
    Q_INVOKABLE void markNotificationsRead();
    Q_INVOKABLE void clearNotifications();
    Q_INVOKABLE void refreshCatalog(const QString&);
    Q_INVOKABLE void setActiveCatalogSource(const QString&);
    Q_INVOKABLE bool isCatalogSourceSelected(const QString&) const;
    Q_INVOKABLE void toggleCatalogSource(const QString&);
    Q_INVOKABLE void applyCatalogSearch(const QString&);
    Q_INVOKABLE void refreshSelectedCatalogs();
    Q_INVOKABLE void pruneDisabledCatalogSources();
    Q_INVOKABLE void selectCatalogSource(const QString&, const QString& = {});
    Q_INVOKABLE void clearCatalogView();
    Q_INVOKABLE int catalogEntryCount(const QString&) const;
    Q_INVOKABLE void prefetchCatalogCounts();
    Q_INVOKABLE void validateHydraCatalogUrl(const QString&, const QString&);
    Q_INVOKABLE void invalidateSourceCatalog(const QString&);
    Q_INVOKABLE void openExternalUrl(const QString&);
    Q_INVOKABLE QString applicationDataPath() const;
    Q_INVOKABLE bool clearApplicationData();
    Q_INVOKABLE bool hasPendingCrashReport() const;
    Q_INVOKABLE QString pendingCrashSummary() const;
    Q_INVOKABLE QString pendingCrashDetails() const;
    Q_INVOKABLE QString pendingCrashReportPath() const;
    Q_INVOKABLE void dismissPendingCrashReport();
    Q_INVOKABLE void openPendingCrashIssue();
    Q_INVOKABLE void revealPendingCrashReport();
    Q_INVOKABLE void copyPendingCrashReport();
    Q_INVOKABLE void requestCatalogCover(const QString&);
    Q_INVOKABLE void cancelCatalogCover(const QString&);
    Q_INVOKABLE void invalidateCatalogCover(const QString&);
    Q_INVOKABLE void enrichCatalogEntry(const QString&);
    void prepareShutdown();
