# -*- coding: utf-8 -*-
"""Replace Russian qsTr() source strings with English."""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1] / "qml"

MAP: dict[str, str] = {
    "%1 активных · докачка после перезапуска": "%1 active · resume after restart",
    "%1 активных загрузок": "%1 active downloads",
    "%1 доп.": "%1 add-ons",
    "%1 доп. · %2 в загрузке": "%1 add-ons · %2 downloading",
    "%1 доп. · готово": "%1 add-ons · done",
    "%1 игр": "%1 games",
    "%1/%2 доп.": "%1/%2 add-ons",
    "JSON-фид games.json по URL — тот же формат, что в Hydra Launcher. Подключите в Настройки → Каталоги Hydra, игры появятся в «Каталоге».": "A games.json feed by URL — the same format as Hydra Launcher. Add it under Settings → Hydra catalogs; games appear in Catalog.",
    "Библиотека": "Library",
    "Библиотека пуста. Установите плагин источника, выберите игру в каталоге — и она появится здесь.": "Your library is empty. Install a source plugin, pick a game in the catalog, and it will show up here.",
    "В библиотеке": "In library",
    "Выберите игру и запустите установку — торрент скачается сам.": "Pick a game and start installation — the torrent downloads automatically.",
    "Выберите раздел — каждый экран отвечает за свою часть настроек.": "Choose a section — each screen covers part of your setup.",
    "Два способа наполнить каталог: каталоги Hydra (games.json) — для перехода с Hydra; плагины (.arach) — полный цикл: каталог, установка, запуск и дополнения.": "Two ways to fill the catalog: Hydra catalogs (games.json) for migrating from Hydra; plugins (.arach) for the full cycle: catalog, install, launch, and add-ons.",
    "Детали игры": "Game details",
    "Дополнения": "Add-ons",
    "Есть обновление": "Update available",
    "Загрузка %1%": "Downloading %1%",
    "Загрузка каталога…": "Loading catalog…",
    "Загрузки": "Downloads",
    "Загрузки продолжаются после перезапуска": "Downloads continue after restart",
    "Загружено": "Downloaded",
    "Задачи": "Tasks",
    "Запущена": "Running",
    "Запущена: %1": "Running: %1",
    "Игра не найдена": "Game not found",
    "Играет": "Playing",
    "Играть": "Play",
    "Источники": "Sources",
    "Каталог": "Catalog",
    "Каталог Hydra": "Hydra catalog",
    "Каталоги Hydra": "Hydra catalogs",
    "Каталоги и плагины": "Catalogs and plugins",
    "Моя библиотека": "My library",
    "Найдено: %1": "Found: %1",
    "Настройки": "Settings",
    "Начните установку из каталога — прогресс появится здесь.": "Start installing from the catalog — progress will appear here.",
    "Недавно играли": "Recently played",
    "Нет загрузок": "No downloads",
    "Обновить": "Refresh",
    "Обновление": "Updating",
    "Обновления": "Updates",
    "Описание пока недоступно.": "Description is not available yet.",
    "Ожидает установки": "Waiting to install",
    "Открыть": "Open",
    "Открыть каталог": "Open catalog",
    "Отмена": "Cancel",
    "Пауза · %1%": "Paused · %1%",
    "Плагин": "Plugin",
    "Плагины": "Plugins",
    "Подробнее": "Details",
    "Пока тут ничего нет": "Nothing here yet",
    "Повторить установку": "Retry install",
    "Проверить файлы": "Verify files",
    "Проверить portable": "Verify portable",
    "Проверить обновления": "Check for updates",
    "Проверка обновлений и целостности portable-сборок.": "Update checks and portable build integrity verification.",
    "Проверять обновления при загрузке каталога": "Check for updates when loading the catalog",
    "Проверять файлы portable перед запуском": "Verify portable files before launch",
    "Путь установки": "Install path",
    "Сейчас играете": "Playing now",
    "Скачать торрент": "Download torrent",
    "Сравнивает даты сборок в каталоге с установленными играми.": "Compares build dates in the catalog with installed games.",
    "Тема и палитра Material 3 применяются ко всему приложению.": "Material 3 theme and palette apply across the app.",
    "Тип установки": "Install type",
    "Торрент загружен. Нажмите «Установить», чтобы плагин источника распаковал или установил игру.": "Torrent downloaded. Click Install for the source plugin to extract or install the game.",
    "Торренты докачиваются после перезапуска": "Torrents resume after restart",
    "Тёмная тема": "Dark theme",
    "Установить": "Install",
    "Установить плагин": "Install plugin",
    "Установите плагин источника (FreeTP и др.) в Настройки → Плагины.": "Install a source plugin (FreeTP, etc.) under Settings → Plugins.",
    "Установка %1%": "Installing %1%",
    "Установка…": "Installing…",
    "Установленные игры живут здесь: запуск, обновления, детали.": "Installed games live here: launch, updates, and details.",
    "Файлы игры будут удалены с диска. Это действие нельзя отменить.": "Game files will be deleted from disk. This cannot be undone.",
    "FreeTP и др. — установка, запуск, дополнения (.arach)": "FreeTP and others — install, launch, add-ons (.arach)",
    "games.json по URL — переход с Hydra Launcher": "games.json by URL — migrate from Hydra Launcher",
    "Папки библиотеки и загрузок": "Library and download folders",
    "Автопроверка и целостность portable": "Auto-check updates and portable integrity",
    "Тема, палитра и акцентный цвет": "Theme, palette, and accent color",
    "Внешний вид": "Appearance",
    "Хранилище": "Storage",
    "Палитра": "Palette",
    "Светлая тема": "Light theme",
    "Папка установки и .exe должны существовать.": "The install folder and .exe must exist.",
    "Игры из включённых каталогов появляются в «Каталоге». Загрузка — через торрент по magnet из JSON.": "Games from enabled catalogs appear in Catalog. Downloads use torrent magnets from JSON.",
    "После загрузки и установки игра окажется здесь — запуск, обновления и детали.": "After download and install, the game appears here — launch, updates, and details.",
    "Шаг 1": "Step 1",
    "Шаг 2": "Step 2",
    "Шаг 3": "Step 3",
    "Язык": "Language",
    "English": "English",
    "Русский": "Russian",
    "Переводы сообщества": "Community translations",
    "Нет вашего языка? Помогите перевести Arachnel на Weblate или отправьте pull request с файлами translations/*.ts.": "Missing your language? Help translate Arachnel on Weblate or send a pull request with translations/*.ts files.",
    "Помочь с переводом": "Help translate",
    "Подключите каталоги в формате Hydra Launcher (games.json). Удобно при переходе с Hydra — те же ссылки на игры, загрузка через торрент. Для установки и запуска нужен плагин источника.": "Connect catalogs in Hydra Launcher format (games.json). Handy when migrating from Hydra — same game links, torrent downloads. A source plugin is required to install and launch.",
    "Пока нет каталогов": "No catalogs yet",
    "Нажмите «Добавить каталог» и вставьте URL вашего games.json — как в Hydra, или публичный фид сообщества.": "Click Add catalog and paste your games.json URL — like Hydra, or a public community feed.",
    "Игр: %1": "Games: %1",
    "Игр: …": "Games: …",
    "Активен в каталоге": "Active in catalog",
    "Выключен": "Disabled",
    "Нет URL — каталог не загрузится": "No URL — catalog will not load",
    "Изменить": "Edit",
    "Удалить": "Delete",
    "Добавить каталог Hydra": "Add Hydra catalog",
    "Плагин · v%1": "Plugin · v%1",
    "Укажите название и URL каталога.": "Enter a name and catalog URL.",
    "Проверка каталога…": "Validating catalog…",
    "Проверка…": "Validating…",
    "Не удалось добавить каталог.": "Could not add catalog.",
    "Не удалось загрузить каталог по этому URL.": "Could not load catalog from this URL.",
    "Не удалось сохранить изменения.": "Could not save changes.",
    "Найдено игр: %1": "Games found: %1",
    "Сохранить": "Save",
    "Добавить": "Add",
    "Название": "Name",
    "URL каталога": "Catalog URL",
    "Описание (необязательно)": "Description (optional)",
    "Включён в каталоге": "Enabled in catalog",
    "Выключен в каталоге": "Disabled in catalog",
    "Редактировать каталог": "Edit catalog",
    "Новый каталог Hydra": "New Hydra catalog",
    "Выберите дополнения": "Select add-ons",
    "Установить выбранные": "Install selected",
    "Обязательные": "Required",
    "Опциональные": "Optional",
    "Выберите место установки": "Choose install location",
    "Использовать библиотеку по умолчанию": "Use default library",
    "Папка библиотеки": "Library folder",
    "Папка загрузок": "Downloads folder",
    "Добавить библиотеку": "Add library",
    "По умолчанию": "Default",
    "Уведомления": "Notifications",
    "Прочитать все": "Mark all read",
    "Очистить все": "Clear all",
    "Нет уведомлений": "No notifications",
    "Остановить": "Stop",
    "Остановить игру": "Stop game",
    "Скрыть панель": "Hide bar",
    "Библиотека": "Library",
    "Каталог": "Catalog",
    "Загрузки": "Downloads",
    "О приложении": "About",
    "Общие": "General",
    "Сортировка": "Sort",
    "Сначала новые": "Newest first",
    "Сначала старые": "Oldest first",
    "По названию А–Я": "Title A–Z",
    "По названию Я–А": "Title Z–A",
    "Выберите источники": "Select sources",
    "Включите один или несколько чипов источников — или оставьте все выключенными.": "Enable one or more source chips — or leave them all off.",
    "Ничего не найдено": "Nothing found",
    "Попробуйте другой запрос или обновите каталог.": "Try another search or refresh the catalog.",
    "Нет игр": "No games",
    "Подключите каталог Hydra в настройках — или установите плагин источника.": "Connect a Hydra catalog in Settings — or install a source plugin.",
    "Добавить каталог": "Add catalog",
    "Источник определяет способ установки — у каждого плагина свой пайплайн.": "The source defines how installation works — each plugin has its own pipeline.",
    "%1 · %2": "%1 · %2",
    "Загрузка…": "Loading…",
    "Удалить игру?": "Remove game?",
    "Удалить из библиотеки": "Remove from library",
    "Удалить каталог?": "Remove catalog?",
    "Открыть папку игры": "Open game folder",
    "Открыть настройки": "Open settings",
    "Очистить завершённые": "Clear completed",
    "Нет плагинов": "No plugins",
    "Установить плагин (.arach)": "Install plugin (.arach)",
    "Открыть папку плагинов": "Open plugins folder",
    "Перезагрузить плагины": "Reload plugins",
    "Включить": "Enable",
    "Выключить": "Disable",
    "Версия: %1": "Version: %1",
    "Состояние": "State",
    "Включён": "Enabled",
    "Библиотеки на дисках — как в Steam. По умолчанию C:, можно добавить другие диски.": "Libraries on disks — like Steam. Default is C:; you can add other drives.",
    "Все": "All",
    "Выберите диск для установки": "Choose a drive for installation",
    "Выберите дополнения для совместной загрузки с игрой.": "Choose add-ons to download together with the game.",
    "Готово": "Done",
    "Далее": "Next",
    "Добавить диск…": "Add drive…",
    "Загрузка · %1%": "Downloading · %1%",
    "Здесь появятся установки, ошибки и другие события.": "Installs, errors, and other events will appear here.",
    "Игры: %1": "Games: %1",
    "Изменить каталог": "Edit catalog",
    "К игре «%1» доступны дополнения — выберите, что скачать вместе с игрой.": "Add-ons are available for \"%1\" — choose what to download with the game.",
    "Каталог Hydra — JSON-фид games.json по ссылке. Arachnel подтянет список игр и magnet-ссылки, как в Hydra Launcher. Установка и запуск — через плагин источника (например FreeTP).": "Hydra catalog — a games.json JSON feed by URL. Arachnel pulls the game list and magnet links like Hydra Launcher. Install and launch via a source plugin (e.g. FreeTP).",
    "Краткое описание (необязательно)": "Short description (optional)",
    "На этом диске пока нет игр": "No games on this drive yet",
    "Назад": "Back",
    "Необяз.": "Optional",
    "Открыть папку": "Open folder",
    "Переместить на диск": "Move to drive",
    "Переместить…": "Move…",
    "Плагины не найдены": "No plugins found",
    "Плагины — источники с каталогом, установкой и запуском. Пакет: файл .arach (ZIP с plugin.json и библиотекой).": "Plugins are sources with catalog, install, and launch. Package: .arach file (ZIP with plugin.json and libraries).",
    "Пока пусто": "Empty for now",
    "Пользовательские: %1": "User-installed: %1",
    "Снять": "Deselect",
    "Установите пакет .arach через кнопку ниже.\\n\\nПосле сборки FreeTP лежит в dist:\\nbuild-win\\dist\\freetp.arach": "Install the .arach package using the button below.\\n\\nAfter building, FreeTP is in dist:\\nbuild-win\\dist\\freetp.arach",
    "Установить .arach…": "Install .arach…",
    "Установить на:": "Install to:",
}

PATTERN = re.compile(r'qsTr\("((?:\\.|[^"\\])*)"\)')
MISSING: list[str] = []


def replace(match: re.Match[str]) -> str:
    text = match.group(1).replace('\\"', '"').replace("\\\\", "\\")
    if text not in MAP:
        if any("\u0400" <= c <= "\u04FF" for c in text):
            MISSING.append(text)
        return match.group(0)
    en = MAP[text].replace("\\", "\\\\").replace('"', '\\"')
    return f'qsTr("{en}")'


def main() -> int:
    changed = 0
    for path in sorted(ROOT.rglob("*.qml")):
        original = path.read_text(encoding="utf-8")
        updated = PATTERN.sub(replace, original)
        if updated != original:
            path.write_text(updated, encoding="utf-8", newline="\n")
            changed += 1
    for text in sorted(set(MISSING)):
        sys.stdout.buffer.write(f"MISSING: {text}\n".encode("utf-8"))
    print(f"Updated {changed} files, {len(set(MISSING))} missing", flush=True)
    return 1 if MISSING else 0


if __name__ == "__main__":
    raise SystemExit(main())
